---
abstract: 'TAP (Test Anything Protocol) parser which supported the subtest'
author:
  - 'magnolia <magnolia.k@me.com>'
build_requires:
  ExtUtils::MakeMaker: '6.98'
  Test::Exception: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.98'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TAP-Tree
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '1.001002'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/magnolia-k/p5-TAP-Tree/issues
  homepage: https://github.com/magnolia-k/p5-TAP-Tree
  repository: https://github.com/magnolia-k/p5-TAP-Tree.git
version: v0.0.3
